spring:
  output:
    ansi:
      enabled: always
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

application:
  locale: ru_RU
  questionsPath: data/questions-answers.csv
  successScore: 4
